
// MarshmallowTableViewCellsConstants.h
// Generated by Rake task

#ifndef MarshmallowTableViewCellsConstants_h
#define MarshmallowTableViewCellsConstants_h

#define kUserTableViewCellHeight          80
#define kMessageTableViewCellBottomHeight 20


#define kTVCUserBackgroundImage          [RBLResizableImage imageNamed:@"userBackground"];
#define kTVCMessageFillImage             [RBLResizableImage imageNamed:@"messageFill"];
#define kTVCMessageBottomSeparatorImage  [RBLResizableImage imageNamed:@"messageBottomSeparator"];
#define kTVCMessageBottomEndImage        [RBLResizableImage imageNamed:@"messageBottomEnd"];

#endif
